##### Postgres Service #####

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./sql_folder:/var/lib/postgresql_01/data 
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
 
